name: run-alert-bot

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allows manual run

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python alerts.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.8413416404:AAFXi9o6COMAePGBZuqEBBCc5xQaC75QX4Y }}
          TELEGRAM_CHAT_ID: ${{ secrets.-1003269191024 }}
          WINDOW_MINUTES: "10"
